{% set name = "django-fernet-fields-v2" %}
{% set version = "0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_fernet_fields_v2-{{ version }}.tar.gz
  sha256: 998476968be1ded3eabb4fa51b27ceddcae295c8227c304f117a3348ece8cbda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cryptography >=0.9
    - django >=4.0
    - python >=3.8

test:
  imports:
    - fernet_fields
    - fernet_fields.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MichelML/django-fernet-fields/
  summary: Fernet-encrypted model fields for Django
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - MichelML
